#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

namespace RepoDb.Connector.AuroraDb.IntegrationTests.Setup
{
    /// <summary>
    /// A class used as a startup setup for the RepoDb Aurora PostgreSQL bulk-operations test database.
    /// </summary>
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string used to reach the Aurora PostgreSQL server itself (the <c>postgres</c> database) -
        /// used only to create the database if it does not already exist.
        /// </summary>
        public static string ConnectionStringForSystem { get; private set; }

        /// <summary>
        /// Gets the connection string to be used for the Aurora PostgreSQL database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        /// <summary>
        /// Initialize the creation of the database.
        /// </summary>
        public static void Initialize()
        {
            ConnectionStringForSystem =
                Environment.GetEnvironmentVariable("REPODB_AURORADB_CONSTR_SYSTEM") ??
                "Host=127.0.0.1;Port=5435;Database=postgres;Username=postgres;Password=RepoDB2026;";

            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_AURORADB_CONSTR") ??
                "Host=127.0.0.1;Port=5435;Database=RepoDb.Connector.AuroraDb;Username=postgres;Password=RepoDB2026;";

            // Create the database first
            CreateDatabase();

            // Create the extensions
            CreateExtensions();

            // Create the tables
            CreateTables();
        }

        /// <summary>
        /// Creates the <c>RepoDb.Connector.AuroraDb</c> database if it does not already exist.
        /// </summary>
        public static void CreateDatabase()
        {
            using var connection = new AuroraDbConnection(ConnectionStringForSystem);
            var exists = Helper.ExecuteScalar<int>(connection,
                "SELECT COUNT(*) FROM pg_database WHERE datname = 'RepoDb.Connector.AuroraDb';");
            if (exists == 0)
            {
                Helper.ExecuteNonQuery(connection, "CREATE DATABASE \"RepoDb.Connector.AuroraDb\";");
            }
        }

        /// <summary>
        /// Clean up all the table.
        /// </summary>
        public static void Cleanup()
        {
            using var connection = new AuroraDbConnection(ConnectionString);
            Helper.ExecuteNonQuery(connection, "TRUNCATE TABLE \"InsertModel\";");
        }

        #endregion

        #region CreateExtensions

        /// <summary>
        /// Creates the extensions required by the native type tests (the <c>citext</c>, <c>ltree</c>, <c>hstore</c> and <c>postgis</c> extensions).
        /// </summary>
        public static void CreateExtensions()
        {
            // Pooling is disabled so that the Npgsql type cache of the pooled connections, used by the tests, is loaded only after the extensions exist.
            using var connection = new AuroraDbConnection(ConnectionString + ";Pooling=false;");
            foreach (var extension in new[] { "citext", "ltree", "hstore", "postgis" })
            {
                Helper.ExecuteNonQuery(connection, $"CREATE EXTENSION IF NOT EXISTS {extension};");
            }
        }

        #endregion

        #region CreateTables

        /// <summary>
        /// Create the necessary tables for testing.
        /// </summary>
        public static void CreateTables()
        {
            CreateInsertTable();
        }

        /// <summary>
        ///
        /// </summary>
        public static void CreateInsertTable()
        {
            var commandText = @"
                CREATE TABLE IF NOT EXISTS ""InsertModel""
                (
                    ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""RowGuid"" UUID NOT NULL,
                    ""ColumnBit"" SMALLINT NULL,
                    ""ColumnDateTime"" TIMESTAMP NULL,
                    ""ColumnDateTime2"" TIMESTAMP(6) NULL,
                    ""ColumnDecimal"" DECIMAL(18,2) NULL,
                    ""ColumnFloat"" DOUBLE PRECISION NULL,
                    ""ColumnInt"" INT4 NULL,
                    ""ColumnNVarChar"" VARCHAR(2000) NULL,
                    PRIMARY KEY (""Id"")
                );";
            using var connection = new AuroraDbConnection(ConnectionString);
            Helper.ExecuteNonQuery(connection, commandText);
        }

        /// <summary>
        ///
        /// </summary>
        public static void CreateBulkOperationNonIdentityTable()
        {
            var commandText = @"
                CREATE TABLE IF NOT EXISTS ""BulkOperationNonIdentityTable""
                (
                    ""Id"" BIGINT NOT NULL,
                    ""RowGuid"" UUID NOT NULL,
                    ""ColumnBit"" SMALLINT NULL,
                    ""ColumnDateTime"" TIMESTAMP NULL,
                    ""ColumnDateTime2"" TIMESTAMP(6) NULL,
                    ""ColumnDecimal"" DECIMAL(18,2) NULL,
                    ""ColumnFloat"" DOUBLE PRECISION NULL,
                    ""ColumnInt"" INT4 NULL,
                    ""ColumnNVarChar"" VARCHAR(2000) NULL,
                    PRIMARY KEY (""Id"")
                );";
            using var connection = new AuroraDbConnection(ConnectionString);
            Helper.ExecuteNonQuery(connection, commandText);
        }

        #endregion
    }
}
