name: repodbconnectors
version: '3.8'

services:

  auroradb:
    container_name: auroradb
    image: postgis/postgis:latest
    ports:
      - 127.0.0.1:5435:5432
    networks:
      - auroradb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RepoDB2026

  auroradbmysql:
    container_name: auroradbmysql
    image: mysql:8.0
    ports:
      - 127.0.0.1:3308:3306
    networks:
      - auroradbmysql
    environment:
      MYSQL_ROOT_PASSWORD: RepoDB2026
    command: --local-infile=1

  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure --listen-addr=0.0.0.0:26257 --http-addr=0.0.0.0:8080
    ports:
      - 127.0.0.1:26257:26257
      - 127.0.0.1:8081:8080
    networks:
      - cockroachdb

  enterprisedb:
    container_name: enterprisedb
    build:
      context: ./src/RepoDb.Connector.EnterpriseDb/Docker
    ports:
      - 127.0.0.1:5433:5444
    networks:
      - enterprisedb
    environment:
      EDB_SUPERUSER: enterprisedb
      EDB_SUPERUSER_PASSWORD: RepoDB2026

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 127.0.0.1:3307:3306
    networks:
      - mariadb
    environment:
      MARIADB_ROOT_PASSWORD: RepoDB2026
    command: --local-infile=1

networks:
  auroradb:
    driver: bridge
  auroradbmysql:
    driver: bridge
  cockroachdb:
    driver: bridge
  enterprisedb:
    driver: bridge
  mariadb:
    driver: bridge