name: mariadb
version: '3.8'

services:

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 127.0.0.1:3307:3306
    networks:
      - mariadb
    environment:
      MARIADB_ROOT_PASSWORD: RepoDB2026
    command: --local-infile=1

  enterprisedb:
    container_name: enterprisedb
    build:
      context: ./src/RepoDb.Connector.EnterpriseDb/Docker
    ports:
      - 127.0.0.1:5433:5444
    networks:
      - enterprisedb
    environment:
      EDB_SUPERUSER: enterprisedb
      EDB_SUPERUSER_PASSWORD: RepoDB2026

networks:
  mariadb:
    driver: bridge
  enterprisedb:
    driver: bridge