#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

namespace RepoDb.Connector.CockroachDb.IntegrationTests.Setup
{
    /// <summary>
    /// A class used as a startup setup for the RepoDb CockroachDB bulk-operations test database.
    /// </summary>
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string used to reach the CockroachDB server itself (the <c>defaultdb</c> database) -
        /// used only to create the database if it does not already exist.
        /// </summary>
        public static string ConnectionStringForSystem { get; private set; }

        /// <summary>
        /// Gets the connection string to be used for the CockroachDB database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        /// <summary>
        /// Initialize the creation of the database.
        /// </summary>
        public static void Initialize()
        {
            ConnectionStringForSystem =
                Environment.GetEnvironmentVariable("REPODB_COCKROACHDB_CONSTR_SYSTEM") ??
                "Host=127.0.0.1;Port=26257;Database=defaultdb;Username=root;SSL Mode=Disable;";

            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_COCKROACHDB_CONSTR") ??
                "Host=127.0.0.1;Port=26257;Database=RepoDb.Connector.CockroachDb;Username=root;SSL Mode=Disable;";

            // Create the database first
            CreateDatabase();

            // Create the tables
            CreateTables();
        }

        /// <summary>
        /// Creates the <c>RepoDb.Connector.CockroachDb</c> database if it does not already exist.
        /// </summary>
        public static void CreateDatabase()
        {
            using var connection = new CockroachDbConnection(ConnectionStringForSystem);
            var exists = Helper.ExecuteScalar<int>(connection,
                "SELECT COUNT(*) FROM pg_database WHERE datname = 'RepoDb.Connector.CockroachDb';");
            if (exists == 0)
            {
                Helper.ExecuteNonQuery(connection, "CREATE DATABASE \"RepoDb.Connector.CockroachDb\";");
            }
        }

        /// <summary>
        /// Clean up all the table.
        /// </summary>
        public static void Cleanup()
        {
            using var connection = new CockroachDbConnection(ConnectionString);
            Helper.ExecuteNonQuery(connection, "TRUNCATE TABLE \"InsertModel\";");
        }

        #endregion

        #region CreateTables

        /// <summary>
        /// Create the necessary tables for testing.
        /// </summary>
        public static void CreateTables()
        {
            CreateInsertTable();
        }

        /// <summary>
        ///
        /// </summary>
        public static void CreateInsertTable()
        {
            var commandText = @"
                CREATE TABLE IF NOT EXISTS ""InsertModel""
                (
                    ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""RowGuid"" UUID NOT NULL,
                    ""ColumnBit"" SMALLINT NULL,
                    ""ColumnDateTime"" TIMESTAMP NULL,
                    ""ColumnDateTime2"" TIMESTAMP(6) NULL,
                    ""ColumnDecimal"" DECIMAL(18,2) NULL,
                    ""ColumnFloat"" DOUBLE PRECISION NULL,
                    ""ColumnInt"" INT4 NULL,
                    ""ColumnNVarChar"" VARCHAR(2000) NULL,
                    PRIMARY KEY (""Id"")
                );";
            Helper.ExecuteNonQuery(new CockroachDbConnection(ConnectionString), commandText);
        }

        /// <summary>
        ///
        /// </summary>
        public static void CreateBulkOperationNonIdentityTable()
        {
            var commandText = @"
                CREATE TABLE IF NOT EXISTS ""BulkOperationNonIdentityTable""
                (
                    ""Id"" BIGINT NOT NULL,
                    ""RowGuid"" UUID NOT NULL,
                    ""ColumnBit"" SMALLINT NULL,
                    ""ColumnDateTime"" TIMESTAMP NULL,
                    ""ColumnDateTime2"" TIMESTAMP(6) NULL,
                    ""ColumnDecimal"" DECIMAL(18,2) NULL,
                    ""ColumnFloat"" DOUBLE PRECISION NULL,
                    ""ColumnInt"" INT4 NULL,
                    ""ColumnNVarChar"" VARCHAR(2000) NULL,
                    PRIMARY KEY (""Id"")
                );";
            using var connection = new CockroachDbConnection(ConnectionString);
            Helper.ExecuteNonQuery(connection, commandText);
        }

        #endregion
    }
}
