#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

namespace RepoDb.Connector.EnterpriseDb.IntegrationTests.Setup
{
    /// <summary>
    /// A class used as a startup setup for the RepoDb EnterpriseDb bulk-operations test database.
    /// </summary>
    public static class Database
    {
        #region Properties

        /// <summary>
        /// Gets the connection string used to reach the EnterpriseDB server itself (the <c>postgres</c> maintenance database) -
        /// used only to create the database if it does not already exist.
        /// </summary>
        public static string ConnectionStringForSystem { get; private set; }

        /// <summary>
        /// Gets the connection string to be used for the EnterpriseDb database.
        /// </summary>
        public static string ConnectionString { get; private set; }

        #endregion

        #region Methods

        /// <summary>
        /// Initialize the creation of the database.
        /// </summary>
        public static void Initialize()
        {
            ConnectionStringForSystem =
                Environment.GetEnvironmentVariable("REPODB_ENTERPRISEDB_CONSTR_SYSTEM") ??
                "Host=127.0.0.1;Port=5433;Database=postgres;Username=enterprisedb;Password=RepoDB2026;";

            ConnectionString =
                Environment.GetEnvironmentVariable("REPODB_ENTERPRISEDB_CONSTR") ??
                "Host=127.0.0.1;Port=5433;Database=RepoDb.Connector.EnterpriseDb;Username=enterprisedb;Password=RepoDB2026;";

            // Create the database first
            CreateDatabase();

            // Create the tables
            CreateTables();
        }

        /// <summary>
        /// Creates the <c>RepoDb.Connector.EnterpriseDb</c> database if it does not already exist.
        /// </summary>
        public static void CreateDatabase()
        {
            using var connection = new EDBConnection(ConnectionStringForSystem);
            var exists = Helper.ExecuteScalar<int>(connection,
                "SELECT COUNT(*) FROM pg_database WHERE datname = 'RepoDb.Connector.EnterpriseDb';");
            if (exists == 0)
            {
                Helper.ExecuteNonQuery(connection, "CREATE DATABASE \"RepoDb.Connector.EnterpriseDb\";");
            }
        }

        /// <summary>
        /// Clean up all the table.
        /// </summary>
        public static void Cleanup()
        {
            using var connection = new EDBConnection(ConnectionString);
            Helper.ExecuteNonQuery(connection, "TRUNCATE TABLE \"InsertModel\" RESTART IDENTITY;");
        }

        #endregion

        #region CreateTables

        /// <summary>
        /// Create the necessary tables for testing.
        /// </summary>
        public static void CreateTables()
        {
            CreateInsertTable();
        }

        /// <summary>
        ///
        /// </summary>
        public static void CreateInsertTable()
        {
            var commandText = @"
                CREATE TABLE IF NOT EXISTS ""InsertModel""
                (
                    ""Id"" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                    ""RowGuid"" UUID NOT NULL,
                    ""ColumnBit"" SMALLINT NULL,
                    ""ColumnDateTime"" TIMESTAMP NULL,
                    ""ColumnDateTime2"" TIMESTAMP(6) NULL,
                    ""ColumnDecimal"" DECIMAL(18,2) NULL,
                    ""ColumnFloat"" DOUBLE PRECISION NULL,
                    ""ColumnInt"" INTEGER NULL,
                    ""ColumnNVarChar"" VARCHAR(2000) NULL,
                    PRIMARY KEY (""Id"")
                );";
            Helper.ExecuteNonQuery(new EDBConnection(ConnectionString), commandText);
        }

        /// <summary>
        ///
        /// </summary>
        public static void CreateBulkOperationNonIdentityTable()
        {
            var commandText = @"
                CREATE TABLE IF NOT EXISTS ""BulkOperationNonIdentityTable""
                (
                    ""Id"" BIGINT NOT NULL,
                    ""RowGuid"" UUID NOT NULL,
                    ""ColumnBit"" SMALLINT NULL,
                    ""ColumnDateTime"" TIMESTAMP NULL,
                    ""ColumnDateTime2"" TIMESTAMP(6) NULL,
                    ""ColumnDecimal"" DECIMAL(18,2) NULL,
                    ""ColumnFloat"" DOUBLE PRECISION NULL,
                    ""ColumnInt"" INTEGER NULL,
                    ""ColumnNVarChar"" VARCHAR(2000) NULL,
                    PRIMARY KEY (""Id"")
                );";
            using var connection = new EDBConnection(ConnectionString);
            Helper.ExecuteNonQuery(connection, commandText);
        }

        #endregion
    }
}
