#region Copyright Attributions

// Copyright (c) 2026 Michael Camara Pendon.
// Licensed under the Apache License, Version 2.0.
// See the LICENSE file in the project root for full license information.

#endregion

using RepoDb.Connector.EnterpriseDb.IntegrationTests.Setup;

namespace RepoDb.Connector.EnterpriseDb.IntegrationTests.Operations
{
    /// <summary>
    /// Integration tests that round-trip every column type declared on the <c>InsertModel</c> table
    /// (see <see cref="Setup.Database.CreateInsertTable"/>) through <see cref="EDBCommand"/> /
    /// <see cref="EDBDataReader"/>, verifying both the value and the CLR type reported for each column.
    /// </summary>
    [TestClass]
    public class EDBTypeTest
    {
        [TestInitialize]
        public void Initialize()
        {
            Database.Initialize();
            Cleanup();
        }

        [TestCleanup]
        public void Cleanup()
        {
            Database.Cleanup();
        }

        #region Helpers

        private static EDBDataReader InsertAndRead(
            EDBConnection connection,
            string columnName,
            object value)
        {
            using (var insertCommand = connection.CreateCommand())
            {
                insertCommand.CommandText =
                    $"INSERT INTO \"InsertModel\" (\"RowGuid\", \"{columnName}\") VALUES (gen_random_uuid(), @value);";
                insertCommand.Parameters.AddWithValue("@value", value);
                insertCommand.ExecuteNonQuery();
            }

            var selectCommand = connection.CreateCommand();
            selectCommand.CommandText = $"SELECT \"{columnName}\" FROM \"InsertModel\" LIMIT 1;";
            var reader = selectCommand.ExecuteReader();
            reader.Read();
            return reader;
        }

        #endregion

        #region Id (BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY)

        [TestMethod]
        public void TestEDBTypeForIdColumn()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();
                using (var insertCommand = connection.CreateCommand())
                {
                    insertCommand.CommandText = "INSERT INTO \"InsertModel\" (\"RowGuid\") VALUES (gen_random_uuid());";
                    insertCommand.ExecuteNonQuery();
                }

                // Act
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = "SELECT \"Id\" FROM \"InsertModel\" LIMIT 1;";
                    using (var reader = command.ExecuteReader())
                    {
                        reader.Read();

                        // Assert
                        Assert.AreEqual(typeof(long), reader.GetFieldType(0));
                        Assert.IsGreaterThan(0L, reader.GetInt64(0));
                        Assert.IsFalse(reader.IsDBNull(0));
                    }
                }
            }
        }

        #endregion

        #region RowGuid (UUID NOT NULL)

        [TestMethod]
        public void TestEDBTypeForRowGuidColumn()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                var expected = Guid.NewGuid();
                connection.Open();
                using (var insertCommand = connection.CreateCommand())
                {
                    insertCommand.CommandText = "INSERT INTO \"InsertModel\" (\"RowGuid\") VALUES (@value);";
                    insertCommand.Parameters.AddWithValue("@value", expected);
                    insertCommand.ExecuteNonQuery();
                }

                // Act
                using (var command = connection.CreateCommand())
                {
                    command.CommandText = "SELECT \"RowGuid\" FROM \"InsertModel\" LIMIT 1;";
                    using (var reader = command.ExecuteReader())
                    {
                        reader.Read();

                        // Assert
                        Assert.AreEqual(typeof(Guid), reader.GetFieldType(0));
                        Assert.AreEqual(expected, reader.GetGuid(0));
                        Assert.IsFalse(reader.IsDBNull(0));
                    }
                }
            }
        }

        #endregion

        #region ColumnBit (SMALLINT NULL)

        [TestMethod]
        public void TestEDBTypeForColumnBit()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnBit", (short)7))
                {
                    // Assert
                    Assert.AreEqual((short)7, reader.GetInt16(0));
                    Assert.IsFalse(reader.IsDBNull(0));
                }
            }
        }

        [TestMethod]
        public void TestEDBTypeForColumnBitWhenNull()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnBit", DBNull.Value))
                {
                    // Assert
                    Assert.IsTrue(reader.IsDBNull(0));
                }
            }
        }

        #endregion

        #region ColumnDateTime (TIMESTAMP NULL)

        [TestMethod]
        public void TestEDBTypeForColumnDateTime()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                var expected = new DateTime(2023, 1, 15, 9, 30, 0);
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnDateTime", expected))
                {
                    // Assert
                    Assert.AreEqual(typeof(DateTime), reader.GetFieldType(0));
                    Assert.AreEqual(expected, reader.GetDateTime(0));
                    Assert.IsFalse(reader.IsDBNull(0));
                }
            }
        }

        [TestMethod]
        public void TestEDBTypeForColumnDateTimeWhenNull()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnDateTime", DBNull.Value))
                {
                    // Assert
                    Assert.IsTrue(reader.IsDBNull(0));
                }
            }
        }

        #endregion

        #region ColumnDateTime2 (TIMESTAMP(6) NULL)

        [TestMethod]
        public void TestEDBTypeForColumnDateTime2()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup - a fractional-second component that is exactly representable at microsecond
                // precision (1234560 ticks = 123456 microseconds), since TIMESTAMP(6) cannot preserve
                // the sub-microsecond (100ns) precision that a .NET DateTime tick can express.
                var expected = new DateTime(2024, 6, 15, 13, 45, 30).AddTicks(1234560);
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnDateTime2", expected))
                {
                    // Assert
                    Assert.AreEqual(typeof(DateTime), reader.GetFieldType(0));
                    Assert.AreEqual(expected, reader.GetDateTime(0));
                    Assert.IsFalse(reader.IsDBNull(0));
                }
            }
        }

        [TestMethod]
        public void TestEDBTypeForColumnDateTime2WhenNull()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnDateTime2", DBNull.Value))
                {
                    // Assert
                    Assert.IsTrue(reader.IsDBNull(0));
                }
            }
        }

        #endregion

        #region ColumnDecimal (DECIMAL(18,2) NULL)

        [TestMethod]
        public void TestEDBTypeForColumnDecimal()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                var expected = 12345.67M;
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnDecimal", expected))
                {
                    // Assert
                    Assert.AreEqual(typeof(decimal), reader.GetFieldType(0));
                    Assert.AreEqual(expected, reader.GetDecimal(0));
                    Assert.IsFalse(reader.IsDBNull(0));
                }
            }
        }

        [TestMethod]
        public void TestEDBTypeForColumnDecimalWhenNull()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnDecimal", DBNull.Value))
                {
                    // Assert
                    Assert.IsTrue(reader.IsDBNull(0));
                }
            }
        }

        #endregion

        #region ColumnFloat (DOUBLE PRECISION NULL)

        [TestMethod]
        public void TestEDBTypeForColumnFloat()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                var expected = 3.14159265358979D;
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnFloat", expected))
                {
                    // Assert
                    Assert.AreEqual(typeof(double), reader.GetFieldType(0));
                    Assert.AreEqual(expected, reader.GetDouble(0));
                    Assert.IsFalse(reader.IsDBNull(0));
                }
            }
        }

        [TestMethod]
        public void TestEDBTypeForColumnFloatWhenNull()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnFloat", DBNull.Value))
                {
                    // Assert
                    Assert.IsTrue(reader.IsDBNull(0));
                }
            }
        }

        #endregion

        #region ColumnInt (INTEGER NULL)

        [TestMethod]
        public void TestEDBTypeForColumnInt()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                var expected = -123456789;
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnInt", expected))
                {
                    // Assert
                    Assert.AreEqual(typeof(int), reader.GetFieldType(0));
                    Assert.AreEqual(expected, reader.GetInt32(0));
                    Assert.IsFalse(reader.IsDBNull(0));
                }
            }
        }

        [TestMethod]
        public void TestEDBTypeForColumnIntWhenNull()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnInt", DBNull.Value))
                {
                    // Assert
                    Assert.IsTrue(reader.IsDBNull(0));
                }
            }
        }

        #endregion

        #region ColumnNVarChar (VARCHAR(2000) NULL)

        [TestMethod]
        public void TestEDBTypeForColumnNVarChar()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                var expected = "EDBTypeTest 日本語 Ünïcödé";
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnNVarChar", expected))
                {
                    // Assert
                    Assert.AreEqual(typeof(string), reader.GetFieldType(0));
                    Assert.AreEqual(expected, reader.GetString(0));
                    Assert.IsFalse(reader.IsDBNull(0));
                }
            }
        }

        [TestMethod]
        public void TestEDBTypeForColumnNVarCharWhenNull()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                connection.Open();

                // Act
                using (var reader = InsertAndRead(connection, "ColumnNVarChar", DBNull.Value))
                {
                    // Assert
                    Assert.IsTrue(reader.IsDBNull(0));
                }
            }
        }

        #endregion

        #region All columns together

        [TestMethod]
        public void TestEDBTypeForAllInsertModelColumnsRoundTrip()
        {
            using (var connection = new EDBConnection(Database.ConnectionString))
            {
                // Setup
                var expectedRowGuid = Guid.NewGuid();
                short expectedColumnBit = 1;
                var expectedColumnDateTime = new DateTime(2022, 11, 3, 8, 0, 0);
                var expectedColumnDateTime2 = new DateTime(2022, 11, 3, 8, 0, 0).AddTicks(7654320);
                var expectedColumnDecimal = 98765.43M;
                var expectedColumnFloat = 2.71828182845905D;
                var expectedColumnInt = 42;
                var expectedColumnNVarChar = "AllInsertModelColumnsRoundTrip";

                connection.Open();
                using (var insertCommand = connection.CreateCommand())
                {
                    insertCommand.CommandText =
                        "INSERT INTO \"InsertModel\" " +
                        "(\"RowGuid\", \"ColumnBit\", \"ColumnDateTime\", \"ColumnDateTime2\", \"ColumnDecimal\", \"ColumnFloat\", \"ColumnInt\", \"ColumnNVarChar\") " +
                        "VALUES " +
                        "(@rowGuid, @columnBit, @columnDateTime, @columnDateTime2, @columnDecimal, @columnFloat, @columnInt, @columnNVarChar);";
                    insertCommand.Parameters.AddWithValue("@rowGuid", expectedRowGuid);
                    insertCommand.Parameters.AddWithValue("@columnBit", expectedColumnBit);
                    insertCommand.Parameters.AddWithValue("@columnDateTime", expectedColumnDateTime);
                    insertCommand.Parameters.AddWithValue("@columnDateTime2", expectedColumnDateTime2);
                    insertCommand.Parameters.AddWithValue("@columnDecimal", expectedColumnDecimal);
                    insertCommand.Parameters.AddWithValue("@columnFloat", expectedColumnFloat);
                    insertCommand.Parameters.AddWithValue("@columnInt", expectedColumnInt);
                    insertCommand.Parameters.AddWithValue("@columnNVarChar", expectedColumnNVarChar);
                    insertCommand.ExecuteNonQuery();
                }

                // Act
                using (var command = connection.CreateCommand())
                {
                    command.CommandText =
                        "SELECT \"Id\", \"RowGuid\", \"ColumnBit\", \"ColumnDateTime\", \"ColumnDateTime2\", \"ColumnDecimal\", \"ColumnFloat\", \"ColumnInt\", \"ColumnNVarChar\" " +
                        "FROM \"InsertModel\" LIMIT 1;";
                    using (var reader = command.ExecuteReader())
                    {
                        reader.Read();

                        // Assert
                        Assert.IsGreaterThan(0L, reader.GetInt64(reader.GetOrdinal("Id")));
                        Assert.AreEqual(expectedRowGuid, reader.GetGuid(reader.GetOrdinal("RowGuid")));
                        Assert.AreEqual(expectedColumnBit, reader.GetInt16(reader.GetOrdinal("ColumnBit")));
                        Assert.AreEqual(expectedColumnDateTime, reader.GetDateTime(reader.GetOrdinal("ColumnDateTime")));
                        Assert.AreEqual(expectedColumnDateTime2, reader.GetDateTime(reader.GetOrdinal("ColumnDateTime2")));
                        Assert.AreEqual(expectedColumnDecimal, reader.GetDecimal(reader.GetOrdinal("ColumnDecimal")));
                        Assert.AreEqual(expectedColumnFloat, reader.GetDouble(reader.GetOrdinal("ColumnFloat")));
                        Assert.AreEqual(expectedColumnInt, reader.GetInt32(reader.GetOrdinal("ColumnInt")));
                        Assert.AreEqual(expectedColumnNVarChar, reader.GetString(reader.GetOrdinal("ColumnNVarChar")));
                    }
                }
            }
        }

        #endregion
    }
}
